# Everything in this section will be available as an environment variable
DB_USERNAME = "victor"
DB_PASSWORD = "F@vourphilic1"

# You can also add other sections if you like.
# The contents of sections as shown below will not become environment variables,
# but they'll be easily accessible from within Streamlit anyway as we show
